Numpy
NumPy는 행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리이다.
NumPy는 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공한다.

In [3]:
import numpy as np

In [8]:
array = np.array([1,2,2,3])
array

array([1, 2, 2, 3])

In [9]:
len(array)

4

In [10]:
len(np.unique(array))

3

In [16]:
nums = np.arange(4,20,4)
print(nums)

[ 4  8 12 16]


In [17]:
np.where(nums%8==0,'8의 배수', '8의 배수 아님')

array(['8의 배수 아님', '8의 배수', '8의 배수 아님', '8의 배수'], dtype='<U8')

Pandas
Pandas는 python 파이썬 외부 공학용 라이브러리이다. (Numpy를 포함하고 기능을 추가로 더 붙인 라이브러리)
데이터를 표 형태의 데이터프레임에 넣어서 쉽게 이용할 수 있게 해주는데, 쉽게 말해서 파이썬의 엑셀 같다.

엑셀로도 가능하지만 대용량 처리를 할 때 속도가 아주 느리다.
그리고 똑같은 작업을 반복해야 할 때 Pandas로 코딩을 해 놓으면 생산성이 훨씬 높다.

머신러닝을 하기 위해 데이터 전처리 과정이 전체 과정의 70%, 나머지가 머신 러닝에 사용된다. 엑셀에 데이터를 받아서 정제하고 쪼개는 일을 할 때 사람이 일일이 하는 것보다 기계가 하면 인력이나 시간이 적게 들어갈 수 있다.

In [19]:
import pandas as pd

In [24]:
ser = pd.Series([1,2,3])
print(ser.index)
print(ser.values)

RangeIndex(start=0, stop=3, step=1)
[1 2 3]


In [27]:
i_ser = pd.Series([1,2,3], index=['a', 'b', 'c'])
print(i_ser)

a    1
b    2
c    3
dtype: int64


In [29]:
a1=pd.array([1,2,3])
a2=pd.array([2,4,6])
a1+a2

<IntegerArray>
[3, 6, 9]
Length: 3, dtype: Int64

In [41]:
# Series Method
ser = pd.Series([0,5,5,5,10])
print(f'합계: {ser.sum()}')
print(f'최소값: {ser.min()}')
print(f'최대값: {ser.max()}')
print(f'평균: {ser.mean()}')
print(f'표준편차: {ser.std()}')
print(f'왜도: {ser.skew()}')
print(f'첨도: {ser.kurt()}')
print(f'고유값: {ser.unique()}')
print(f'최소값 위치: {ser.idxmin()}')
print(f'최대값 위치: {ser.idxmax()}')
print(f'포함여부 검사: {ser.isin([0,6,10])}')
print(f'포함 개수: {ser.isin([0,6,10]).sum()}')

합계: 25
최소값: 0
최대값: 10
평균: 5.0
표준편차: 3.5355339059327378
왜도: 0.0
첨도: 2.0
고유값: [ 0  5 10]
최소값 위치: 0
최대값 위치: 4
포함여부 검사: 0     True
1    False
2    False
3    False
4     True
dtype: bool
포함 개수: 2


In [80]:
# DataFrame (Pandas의 2차원 객체)
df = pd.DataFrame({"aa": [1,2,3,4,1], "bb": [2,3,4,5,2], "cc": [3,4,5,6,3]})
print(f'데이터프레임: \n{df}\n')
print(f'정수 기반 인덱싱: \n{df.iloc[:3]}\n')
print(f'정수 기반 인덱싱(열 설정): \n{df.iloc[:3,:2]}\n')
print(f'문자열 기반 인덱싱: \n{df.loc[:3]}\n')
print(f'문자열 인덱싱(열 설정): \n{df.loc[:,"aa"::2]}\n')
print(f'빈도표: \n{pd.crosstab(df["aa"],df["cc"])}\n')
print(f'특정변수 기준 요약연산: \n{df.groupby("aa")["bb"].sum()}\n')

데이터프레임: 
   aa  bb  cc
0   1   2   3
1   2   3   4
2   3   4   5
3   4   5   6
4   1   2   3

정수 기반 인덱싱: 
   aa  bb  cc
0   1   2   3
1   2   3   4
2   3   4   5

정수 기반 인덱싱(열 설정): 
   aa  bb
0   1   2
1   2   3
2   3   4

문자열 기반 인덱싱: 
   aa  bb  cc
0   1   2   3
1   2   3   4
2   3   4   5
3   4   5   6

문자열 인덱싱(열 설정): 
   aa  cc
0   1   3
1   2   4
2   3   5
3   4   6
4   1   3

빈도표: 
cc  3  4  5  6
aa            
1   2  0  0  0
2   0  1  0  0
3   0  0  1  0
4   0  0  0  1

특정변수 기준 요약연산: 
aa
1    4
2    3
3    4
4    5
Name: bb, dtype: int64

